### ISSUE TITLE
Training objective

### ISSUE THREAD

**Issue by bakszero** [wise-east/spolin#7]
Hi Justin,

Really nice piece of work! I had a question about the paper, specifically relating to the training objective.
In the paper, you mention the following:

> 2. Predicting the next correct candidate that best fits the dialogue given the dialogue history. 

and

> while the candidate classification head is trained from scratch.

My question is how did you incorporate this into the training? Does it resemble a multi-task setup, if so could you point me to the relevant lines in the code wherein how it is done for the paper?

Thanks!

**Comment by wise-east** [comment]
Hi! 

Yes, this is a multi-task setup. 

I'm sorry that the code for that part of the paper is not available in this repo. As mentioned in the paper, I used the implementation by Wolf et al. 2019 and I forked [their repo](https://github.com/huggingface/transfer-learning-conv-ai).  

The model itself is from the huggingface library and is called `GPT2DoubleHead`. You can find it being initialized [here](https://github.com/huggingface/transfer-learning-conv-ai/blob/d4c760731e8f062abd3d61ccdc8fa29ccb5e3485/train.py#L156) as part of the code in the repo that I mentioned above. You'll need to format your data for the next turn classification task, but it is quite simple. You can read their [workshop paper](http://arxiv.org/abs/1901.08149) for more detail. 

I hope this answers your question! I used this model to train dialogue models for our evaluation, but in the demo at https://spolin.isi.edu, I used [DialoGPT](https://github.com/microsoft/DialoGPT) as it was a more recent model pretrained with larger amounts of data. If your interest is in building a dialogue model, DialoGPT might suit your needs better. 

Hope this helps!

**Comment by bakszero** [comment]
Thanks Justin! This is very helpful.
Cheers!
